### ISSUE TITLE
GPL Relicensing

### ISSUE THREAD

**Issue by koush** [koush/scrypted-ha-addon#1]
Hi @aegjoyce

Thanks again for this project. As we discussed I wanted to make the HA add-on official in the Scrypted repo, but can't do that while it is GPL licensed and needed a permissive or unlimited license (below is copy pasta CLA typically used for this):

> You grant @koush, and those who receive the Submission directly or indirectly from @koush, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third parties.

Paste the above in your reply "yes" if you are ok with this! Thanks.

**Comment by aegjoyce** [comment]
I grant @koush, and those who receive the Submission directly or indirectly from @koush, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third parties.
